#manipulator:
#  kinematics_solver: ur_kinematics/UR3KinematicsPlugin
#  kinematics_solver_search_resolution: 0.005
#  kinematics_solver_timeout: 0.005
manipulator:
  kinematics_solver: bio_ik/BioIKKinematicsPlugin
  solve_type: Distance
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
